### ISSUE TITLE
Problems hashing PS2 games (differences with PCSX2 hashing implementation?)

### ISSUE THREAD

**Issue by retroNUC** [RetroAchievements/rcheevos#225]
[LaunchBox](https://www.launchbox-app.com/) recently integrated rcheevos library for hashing of files in their frontend, but it's failing quite often when identifying PS2 CHD games (returning an error, not returning the wrong hash).

I opened an issue with them here: https://bitbucket.org/jasondavidcarr/launchbox/issues/7624/retroachievements-scan-inconsistent-spotty

Looking at the PCSX2 implementation for comparison, looks like they're not using ra_hash_ps2 directly? Wonder if there's any inconsistencies between the two.

**PCSX2:** https://github.com/PCSX2/pcsx2/blob/master/pcsx2/Frontend/Achievements.cpp#L1380

**Comment by Jamiras** [comment]
PCSX2 is the only emulator that currently supports achievements for PS2, so whatever they're doing for hashing is the only way hashes are currently generated. The rcheevos implementation is meant to be a reference implementation, but it's currently only used by the command line tool (RAHasher).

Note that rcheevos does not implicitly support CHD. The client has to implement a cdreader that wraps the CHD calls. See https://github.com/RetroAchievements/RALibretro/pull/345/files#diff-c69833071a4c40f79b5531f3548bd295b1099f173f5e3d3c8f83a3dae1f6bf23R327-R337 for the RAlibretro implementation.

However, if that were the case, I'd expect _all_ CHD files to fail, not just "quite often" and not just PS2.

**Comment by retroNUC** [comment]
I've verified that the files LB was having problems hashing are identified just fine with rahasher, so it's not a problem with the reference implementation. Closing this one, thanks.
