### ISSUE TITLE
Continue parsing Rich Presence LUTs after encountering commented lines

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/rcheevos#23]
This is a request for a behavioral change.

When defining large look-up tables, I sometimes want to document gaps, or sets of values, as such:
```
Lookup:CharacterTable
// Uppercase letters
0x00=A
0x01=B
(...)
0x19=Z
// Gap -> lowercase letters
0x20=a
(...)
```

Currently, this is not feasible without workarounds, because parsing of a LUT is aborted at the first line with no defined element, or perhaps because the comments are stripped before being parsed and the parser sees only a blank line, and thus the end of the LUT.

Since the syntax is relatively limited there is no perfect solution that I can think of, but I would suggest continuing parsing tables until their scope is ended explicitly (i.e. until the next Lookup, Format, or Display keyword), and/or until a non-blank, non-comment line that cannot be parsed into a table entry is reached.

**Comment by Jamiras** [comment]
Trailing comments are allowed and removed. Trailing whitespace is also removed when removing a trailing comment.

You could do something like this:
```
Lookup:CharacterTable
0x00=A // start of uppercase
0x01=B
(...)
0x19=Z
0x20=a // start of lowercase
(...)
```

**Comment by rzumer** [comment]
> Trailing whitespace is also removed when removing a trailing comment.

Is this a recent addition? I seem to recall spaces preceding trailing comments being displayed. Either way, it is not directly relevant to this issue, but while this makes appended comments less ugly, it also makes documenting entries with deliberate trailing spaces on the same line impossible.

My earlier example was not the best, but the solution you propose is fine for that situation. Sometimes I would like to document a gap between blocks of values without necessarily categorizing them, in which case it is a bit more awkward. It would also be more readable in my opinion to be able to use new lines for commenting blocks of values and only appending comments to existing lines in order to comment individual values. The following example should hopefully better represent how that would help.
```
Lookup:CT
(...)
// special characters
0x4A=// padding (no character)
0x4B=!
0x4C=?
// ignore aberrant characters
0x50=~
(...)
```

It is possible to get around the restriction by just writing longer comments on the end of lines, or inserting dummy values to get more usable lines for comments, but it would be nice to have more flexibility.

**Comment by Jamiras** [comment]
> Is this a recent addition? 

No, trailing whitespace has been removed from lines with comments since comments were [added in 0.73](https://github.com/RetroAchievements/RAIntegration/pull/80/files#diff-08ecf02db53d3c1b03c063e87dca103fR163).

If no trailing comment is present, the whitespace is assumed to be significant.

I wasn't proposing the trailing comment was the final solution, it's just something that's available now.

I believe the actual solution is to not end a block until another block or the end of file is reached. This is significantly more difficult than simply watching for an empty line as each block has its own parsing function, but doable.
