### ISSUE TITLE
[Hashing] Monster Rancher 1 / Monster Rancher 2 need supported ways to switch discs

### ISSUE THREAD

**Issue by pandakar-gaming** [RetroAchievements/rcheevos#330]
The two games in question here: 

- https://retroachievements.org/game/16343 - Monster Rancher / Monster Farm
- https://retroachievements.org/game/11287 - Monster Rancher 2 / Monster Farm 2

These games are both single disc games and have a single supported hash. This works for the core mechanics of the game. However, one of the core gimmicks with these games is the ability to hot-swap arbitrary discs, read data from said discs, and generate usable monsters from them. This was done on console by getting to an in-game location called the Shrine, which would prompt you to insert another disc and move forward like the following image indicates.

![image](https://github.com/RetroAchievements/rcheevos/assets/143897436/16c0b441-8b35-4a15-ab86-88d4b9e3ec84)

To fully support these games in a way that allows for achievements, we would need some common hash that can be used as a basis for generating disc image data that contains different monsters. Other tools out there in the Monster Rancher community support generating discs already, and as of writing none of them write the data needed for RetroAchievements to hash them. Specifically, they don't write the contents of a SYSTEM.CNF file and any associated data from that needed. 

To reiterate the core issue: Monster Rancher and Monster Rancher 2 are single-disc PSX games that support and encourage hot-swapping discs to get different monsters. Currently RetroAchievements recognizes a single hash for each of these games. What can be done to try and get a common hash setup for either of these games to allow for the hot-swapping disc mechanic?

Helpful resources from the Monster Rancher community around current monster generation tools:

- https://legendcup.com/make-a-monster-mr1.php - this is a front-end for generating a BIN+CUE pair for Monster Rancher.
- https://github.com/OmnigamerSDA/MonsterMaker - repo for building a .exe that can generate a BIN+CUE pair for Monster Rancher.
- https://legendcup.com/make-a-monster-mr2.php - this is a front-end for generating a BIN+CUE pair for Monster Rancher 2.

**Comment by Jamiras** [comment]
We already support this for Vib-Ribbon. Just create a custom .m3u with your additional non-game discs, and when you switch between discs, as long as they're not game discs, the hash won't change and the game won't be unloaded.

There's a guide for Vib-Ribbon here: https://retroachievements.org/viewtopic.php?t=11871&c=74178#74178

Monster Rancher is even mentioned in the PR that originally added support: https://github.com/RetroAchievements/RALibretro/pull/307

**Comment by pandakar-gaming** [comment]
Hey,

Apologies. I may have gotten misled by another behaviour when I had been looking at this originally. One of the concerns that I had when I was going through this was that if one were to hot-swap discs, the hash would change based off the disc and flip the user out of Hardcore mode.

I'm testing this again and noting that if I use a .m3u file as you mention, then switching from the Monster Rancher game disc to a non-game disc keeps me in Hardcore mode. If that hadn't been the case then maybe there would be something to do, but as it stands I believe we're fine.

Thanks for the associated guide and the relevant PR link. I'm going to close this one as a non-issue.
