### ISSUE TITLE
.rvz management for gamecube games

### ISSUE THREAD

**Issue by Tartifless** [RetroAchievements/rcheevos#356]
Hello,

Would it be possible to implement .rvz decompression in order to be able to hash game files which are this format ?

**Comment by CasualPokePlayer** [comment]
.rvz is like .chd, in which the client is expected to add in custom file readers to hash them. Also like .chd, .rvz has a variety of possible compression formats, and thus requiring a ton of code to be added to just support this format, which also doubly doesn't make much sense in rcheevos as it is a Dolphin specific format, which Dolphin already handles perfectly fine.

**Comment by Jamiras** [comment]
Agreed. `.rvz` is a custom compression format, and requires very specific code to handle it. It's not something I'd want to distribute as part of this library - even as a dependency/submodule.
