### ISSUE TITLE
Hit counting leaderboard value is not reset between submissions if a leaderboard starts and submits in the same frame

### ISSUE THREAD

**Issue by fomdt** [RetroAchievements/rcheevos#372]
For example, a leaderboard with VAL `M:1=1` should always submit 1 if it happens to start and submit in the same frame, but the actual submitted value is 1 greater than the previous one.

**Comment by redwizard42** [comment]
Why use hit counts for start+submit style?

Just use M:1

**Comment by Jamiras** [comment]
I can see why the code is doing this, but I don't see why _you're_ doing this.

If the value is reset when the leaderboard starts, and the it's updated when the leaderboard submits, the value being submitted would always be 0 or 1, depending on whether or not the related condition was true for the current frame. That doesn't provide a lot of room for people to improve their scores.

**Comment by fomdt** [comment]
I rewrote the opening comment.

An example of such a leaderboard is the time spent in a certain zone or state, which submits on death. If a player enters the zone and dies simultaneously, the previously submitted score will get improved by 1.

Ultimately, whether such a leaderboard is poorly designed or can be written differently is not as important as whether such behaviour is intended.
