### ISSUE TITLE
RC_FORMAT_FRAMES is inaccurate/a misnomer depending on platform/region

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/rcheevos#38]
RC_FORMAT_FRAMES assumes 60fps, but this is not true for PAL-optimized titles (50Hz) or some platforms like Wonderswan that runs at 75Hz. It should be renamed or parameterized to avoid confusion.

**Comment by Hedda** [comment]
@Jamiras is still an issue?

**Comment by ScottFromDerby** [comment]
My bad - it was from when I had first added leaderboards, there was only Mega Drive at the time. I was trying to force (encourage) everyone to use NTSC, otherwise the PAL (slower) leaderboards wouldn't be fair, or at least they would have to be separate, which didn't feel right. Still not sure even now what the right thing is to do

**Comment by Jamiras** [comment]
Not an issue so much as a misnomer. If the system isn't running at 60Hz, you can use `MILLISECS` (also a misnomer - it's actually hundredths of a second) and create a factor to adjust the value. `FRAMES` is just `MILLISECS` with a factor of 1.666666 (100/60). For 75Hz, your factor would be 1.333333 (100/75).

i.e.
```
0xW1234*1.333333
```
would give you the value to use when converting a frame counter on a 75Hz system.

**Comment by Jamiras** [comment]
From an API perspective, both of these constants have the same behavior they've always had. The leaderboard author is responsible for using an alternative when the implementation doesn't work for their particular game.

**Comment by Jamiras** [comment]
I've updated the documentation for [Leaderboards](https://github.com/RetroAchievements/docs/wiki/Leaderboards#value-format) and [Rich Presence](https://github.com/RetroAchievements/docs/wiki/Rich-Presence#format) to clarify that FRAMES is only valid for 60Hz systems.

As I don't intend to make any changes to the code, and there is a reasonable workaround, I'm going to close this.
