### ISSUE TITLE
Slow login on RetroArch

### ISSUE THREAD

**Issue by fr500** [RetroAchievements/rcheevos#5]
Just tried SNES9x on Windows with the latest RA commit, tried super mario all-stars and super mario world.
Tested on commit https://github.com/libretro/RetroArch/commit/ead5b2c0f7848458a22a7102000d8ce22ced1898

SMAS takes roughly a minute to get the achievements.
SMW takes less, around 20 seconds.

**Comment by leiradel** [comment]
We may have to roll this one back: https://github.com/libretro/RetroArch/pull/7201

**Comment by leiradel** [comment]
It makes a HTTP request for RetroAchievements for every 16 KiB of ROM, so I think it can.

**Comment by rzumer** [comment]
See https://github.com/libretro/RetroArch/pull/7333
