### ISSUE TITLE
Achievements never load in RetroArch Android AARCH64, close content with achievements enabled causes it to get stuck.

### ISSUE THREAD

**Issue by fr500** [RetroAchievements/rcheevos#7]
It seems the new implementation has different issues on AARCH64.
The achievement list never finishes loading (the logging message never pops-up) and this causes RA to stop responding on close content.

To verify I disabled achievements entirely and close content then works just fine.
This was tested on a Shield Android TV, running RetroArch AARCH64 https://github.com/libretro/RetroArch/commit/77fba6d58dd4aece400b35b161e6184145275c41

**Comment by fr500** [comment]
I was testing everything with SNES9x, but to verify I tried now with mGBA. Same behavior.

**Comment by meleu** [comment]
this doesn't seem to be an issue anymore.
closing.
